#!/usr/bin/python

import sys
import socket
import time
import datetime
import select
import json
import urlparse

#########################
##  HTTP STATUS CODES  ##
#########################


## 200 - All clear
## 301 - HTTP redirect: crawler should retry request using url returned in Location header
## 403 - Forbidden: crawler should abandon the URL that generated the error code
## 404 - Not Found: crawler should abandon the URL that generated the error code
## 500 - Internal Server Error: crawler should retry the request until successful


########################
##  GLOBAL VARIABLES  ##
########################


usernameMatt = 00005716
passwordMatt = 'YG99AKBL'

domain = 'http://fring.ccs.neu.edu/'
httpPrefix = 'fakebook/'
